/**
 * Fixture data for memory pipeline integration tests.
 *
 * Transcripts are minimal but structurally realistic (matching provider formats).
 * LLM outputs were generated by running the actual summarization prompt through
 * inference() — real model responses, not hand-crafted. The Claude output includes
 * markdown code fences (common LLM behavior) to exercise fence-stripping.
 */

import type { SessionMetadata } from "../../../src/memory/summarize";

// ── Claude Code fixtures ─────────────────────────────────────────────

export const CLAUDE_JSONL = [
  '{"type":"user","uuid":"u1","message":{"role":"user","content":"I need to add rate limiting to our API endpoints. We\'re getting hammered by bots."}}',
  '{"type":"assistant","uuid":"a1","message":{"role":"assistant","content":[{"type":"text","text":"I\'ll help with that. Let me look at your current middleware setup."},{"type":"tool_use","name":"Read"},{"type":"tool_use","name":"Bash"}]}}',
  '{"type":"user","uuid":"u2","message":{"role":"user","content":"The Express middleware is in src/middleware/. We\'re using Redis for sessions already."}}',
  '{"type":"assistant","uuid":"a2","message":{"role":"assistant","content":[{"type":"text","text":"I see the existing setup. I\'ll implement a sliding window rate limiter using your Redis instance.\\n\\n1. Create a new middleware `src/middleware/rate-limit.ts`\\n2. Use Redis MULTI/EXEC for atomic window tracking\\n3. Add per-route configuration"},{"type":"tool_use","name":"Write"},{"type":"tool_use","name":"Write"},{"type":"tool_use","name":"Bash"}]}}',
  '{"type":"user","uuid":"u3","message":{"role":"user","content":"Looks good. Can you add the tests too?"}}',
  '{"type":"assistant","uuid":"a3","message":{"role":"assistant","content":[{"type":"text","text":"Done. I\'ve added:\\n- `src/middleware/rate-limit.ts` — sliding window rate limiter\\n- `test/middleware/rate-limit.test.ts` — 12 tests covering normal flow, burst detection, and Redis failure fallback\\n- Updated `src/app.ts` to apply rate limiting to `/api/*` routes\\n\\nAll tests pass. The rate limiter defaults to 100 requests per 15-minute window per IP, configurable per route."},{"type":"tool_use","name":"Write"},{"type":"tool_use","name":"Bash"}]}}',
].join("\n");

export const CLAUDE_METADATA: SessionMetadata = {
  date: "2026-02-09",
  cwd: "/projects/api-server",
  provider: "claude",
  sessionId: "ses-claude-fixture",
};

/** Generated by inference() — includes ```markdown fences (real LLM behavior) */
export const CLAUDE_LLM_OUTPUT = `\`\`\`markdown
---
date: 2026-02-09
cwd: /projects/api-server
tags: [express, rate-limiting, redis, middleware, security]
provider: claude
session_id: ses-claude-fixture
---

# API Rate Limiting Implementation

## Summary
Implemented a sliding window rate limiter middleware for the Express application using the existing Redis infrastructure to mitigate bot traffic. The solution includes a flexible configuration defaulting to 100 requests per 15-minute window, applied globally to \`/api/*\` routes. Comprehensive tests were added to cover normal traffic, burst detection, and Redis failure scenarios.

## Decisions
- **Redis Backed Storage:** Leveraged the existing Redis instance for state management to avoid introducing new infrastructure dependencies and to support distributed state.
- **Sliding Window Algorithm:** Selected for accurate tracking to prevent "boundary hopping" attacks common with fixed-window counters.
- **Atomic Transactions:** Utilized Redis \`MULTI/EXEC\` to prevent race conditions during concurrent request updates.
- **Per-route Configuration:** Designed the middleware to allow specific routes to override global defaults for flexibility.

## Files Modified
- **Created:** \`src/middleware/rate-limit.ts\` (Core logic)
- **Created:** \`test/middleware/rate-limit.test.ts\` (Test suite)
- **Modified:** \`src/app.ts\` (Middleware application)

## Problems Solved
- **Bot Mitigation:** Stopped excessive request volume from bots by enforcing strict rate limits.
- **Concurrency Safety:** Ensured accurate counting under high load using Redis atomic operations.
- **Reliability:** Verified system behavior under failure conditions (Redis downtime) via unit tests.

## Open Questions
- None explicitly mentioned in transcript.
\`\`\``;

// ── opencode fixtures ────────────────────────────────────────────────

export const OPENCODE_EXPORT = JSON.stringify({
  messages: [
    {
      info: { role: "user" },
      parts: [
        {
          type: "text",
          text: "Fix the broken CSS grid layout on the dashboard. Cards are overlapping on mobile.",
        },
      ],
    },
    {
      info: { role: "assistant" },
      parts: [
        { type: "text", text: "Let me check the current styles." },
        { type: "tool", tool: "Read" },
        {
          type: "text",
          text: "I see the issue. The grid template is using fixed pixel widths instead of responsive units. I'll fix the grid to use `auto-fill` with `minmax` and add a media query for mobile.",
        },
        { type: "tool", tool: "Write" },
        { type: "tool", tool: "Bash" },
      ],
    },
    {
      info: { role: "user" },
      parts: [
        {
          type: "text",
          text: "Perfect, also the sidebar collapses weirdly on tablet sizes.",
        },
      ],
    },
    {
      info: { role: "assistant" },
      parts: [
        {
          type: "text",
          text: "Fixed both issues:\n\n1. Dashboard grid now uses `grid-template-columns: repeat(auto-fill, minmax(280px, 1fr))` — cards flow naturally at all sizes\n2. Sidebar uses a CSS container query instead of a viewport media query, so it collapses based on available space, not screen width\n\nModified files:\n- `src/styles/dashboard.css` — grid layout fix\n- `src/styles/sidebar.css` — container query for tablet\n- `src/components/Sidebar.tsx` — added container wrapper div",
        },
        { type: "tool", tool: "Write" },
        { type: "tool", tool: "Write" },
        { type: "tool", tool: "Write" },
      ],
    },
  ],
});

export const OPENCODE_METADATA: SessionMetadata = {
  date: "2026-02-08",
  cwd: "/projects/dashboard",
  provider: "opencode",
  sessionId: "ses-opencode-fixture",
};

/** Generated by inference() — clean output without code fences */
export const OPENCODE_LLM_OUTPUT = `---
date: 2026-02-08
cwd: /projects/dashboard
tags: [css, responsive-design, grid-layout, container-queries, ui-fix]
provider: opencode
session_id: ses-opencode-fixture
---

# Dashboard Layout & Sidebar Responsiveness Fixes

## Summary
Resolved critical layout regressions where dashboard cards were overlapping on mobile devices and the sidebar collapsed incorrectly on tablet screens. Implemented modern CSS grid features and container queries to create a robust, fluid layout that adapts naturally to available space rather than relying on brittle fixed breakpoints.

## Decisions
- **Grid Auto-Fill Strategy:** Switched the dashboard grid from fixed pixel widths to \`repeat(auto-fill, minmax(280px, 1fr))\`. This allows cards to automatically wrap and resize based on available width without requiring manual media queries for every screen size.
- **Container Queries:** Transitioned the Sidebar component to use CSS container queries (\`@container\`) instead of viewport media queries. This ensures the sidebar adapts based on the actual space allocated to it within the layout, rather than the global screen width, fixing the tablet collapse issue.

## Files Modified
- \`src/styles/dashboard.css\` — Updated grid template definitions.
- \`src/styles/sidebar.css\` — Replaced media queries with container queries.
- \`src/components/Sidebar.tsx\` — Added necessary container wrapper markup.

## Problems Solved
- **Mobile Content Overlap:** Fixed an issue where dashboard cards would stack on top of each other on mobile screens due to rigid pixel definitions.
- **Tablet Layout Instability:** Resolved awkward collapsing behavior in the sidebar on intermediate screen sizes (tablets) by making the component responsive to its parent container.

## Open Questions
- None identified in the transcript.`;
